### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/client' during yo vulcan

### ISSUE THREAD

**Issue by tomachinz** [qtheninja/vulcanscaffold#1]
13inch:vulcanscaffold tom$ sudo yo vulcan

? Your project name generator vulcan
generator vulcan
all done *********************
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/client'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at sync (/Users/tom/GitHub/vulcanscaffold/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/tom/GitHub/vulcanscaffold/node_modules/mkdirp/index.js:77:24)
    at module.exports.yeoman.generators.Base.extend.writing.app (/Users/tom/GitHub/vulcanscaffold/generators/app/index.js:61:12)
    at /Users/tom/GitHub/vulcanscaffold/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback](timers.js:383:17)
13inch:vulcanscaffold tom$ Error: EACCES: permission denied, mkdir '/client'

13inch:vulcanscaffold tom$ node -v
v4.4.5
13inch:vulcanscaffold tom$ npm -v
3.9.3

**Comment by CodyHigdem** [comment]
At first this looked like a permissions problem but it seems to be specific to the MKIRP manipulation of the file system. So I think this would solve most people's problems: https://docs.npmjs.com/getting-started/fixing-npm-permissions

But instead of having a constant hangup that requires additional manipulation I've updated Vulcan Scaffold to instead use a fs.copy for the one empty folder (I added a readme to it which may come in handy since it's the compatibility folder that's empty). 

Update the version of Vulcan you're using and let me know if that fixes it. If it does not try the link above for permission changes. I was able to replicate the problem and resolve it by using the newer version.

**Comment by tomachinz** [comment]
I tried the permission updates on that link (to no avail), and then attempted to fully uninstall node and re-install using brew. Still seem to be stuck. Cheers for the help though! 

13inch:vulcanscaffold tom$ node -v
v4.4.5
13inch:vulcanscaffold tom$ which node
/usr/local/bin/node
13inch:vulcanscaffold tom$ brew uninstall node
Uninstalling /usr/local/Cellar/node/6.3.1... (3,829 files, 40.0M)
13inch:vulcanscaffold tom$ brew prune
Pruned 66 symbolic links and 12 directories from /usr/local
13inch:vulcanscaffold tom$ rm -f /usr/local/bin/npm;
13inch:vulcanscaffold tom$ rm -f /usr/local/lib/dtrace/node.d;
rm: /usr/local/lib/dtrace/node.d: Permission denied
13inch:vulcanscaffold tom$ sudo 'rm -f /usr/local/lib/dtrace/node.d;

> 13inch:vulcanscaffold tom$ sudo rm -f /usr/local/lib/dtrace/node.d;
> Password:
> 13inch:vulcanscaffold tom$ rm -rf ~/.npm;
> 13inch:vulcanscaffold tom$ brew install node;
> ==> Downloading https://homebrew.bintray.com/bottles/node-6.3.1.yosemite.bottle.tar.gz
> Already downloaded: /Users/tom/Library/Caches/Homebrew/node-6.3.1.yosemite.bottle.tar.gz
> ==> Pouring node-6.3.1.yosemite.bottle.tar.gz
> Error: The `brew link` step did not complete successfully
> The formula built, but is not symlinked into /usr/local
> Could not symlink bin/node
> Target /usr/local/bin/node
> already exists. You may want to remove it:
>   rm '/usr/local/bin/node'

To force the link and overwrite all conflicting files:
  brew link --overwrite node

To list all files that would be deleted:
  brew link --overwrite --dry-run node

Possible conflicting files are:
/usr/local/bin/node
/usr/local/include/node/android-ifaddrs.h
/usr/local/include/node/ares.h
/usr/local/include/node/ares_version.h
/usr/local/include/node/common.gypi
/usr/local/include/node/config.gypi
/usr/local/include/node/libplatform/libplatform.h
/usr/local/include/node/nameser.h
/usr/local/include/node/node.h
/usr/local/include/node/node_buffer.h
/usr/local/include/node/node_object_wrap.h
/usr/local/include/node/node_version.h
/usr/local/include/node/openssl/aes.h
/usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
/usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
/usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
/usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
/usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
/usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
/usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
/usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
/usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
/usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
/usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
/usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
/usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
/usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
/usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
/usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
/usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
/usr/local/include/node/openssl/asn1.h
/usr/local/include/node/openssl/asn1_mac.h
/usr/local/include/node/openssl/asn1t.h
/usr/local/include/node/openssl/bio.h
/usr/local/include/node/openssl/blowfish.h
/usr/local/include/node/openssl/bn.h
/usr/local/include/node/openssl/buffer.h
/usr/local/include/node/openssl/camellia.h
/usr/local/include/node/openssl/cast.h
/usr/local/include/node/openssl/cmac.h
/usr/local/include/node/openssl/cms.h
/usr/local/include/node/openssl/comp.h
/usr/local/include/node/openssl/conf.h
/usr/local/include/node/openssl/conf_api.h
/usr/local/include/node/openssl/crypto.h
/usr/local/include/node/openssl/des.h
/usr/local/include/node/openssl/des_old.h
/usr/local/include/node/openssl/dh.h
/usr/local/include/node/openssl/dsa.h
/usr/local/include/node/openssl/dso.h
/usr/local/include/node/openssl/dtls1.h
/usr/local/include/node/openssl/e_os2.h
/usr/local/include/node/openssl/ebcdic.h
/usr/local/include/node/openssl/ec.h
/usr/local/include/node/openssl/ecdh.h
/usr/local/include/node/openssl/ecdsa.h
/usr/local/include/node/openssl/engine.h
/usr/local/include/node/openssl/err.h
/usr/local/include/node/openssl/evp.h
/usr/local/include/node/openssl/hmac.h
/usr/local/include/node/openssl/idea.h
/usr/local/include/node/openssl/krb5_asn.h
/usr/local/include/node/openssl/kssl.h
/usr/local/include/node/openssl/lhash.h
/usr/local/include/node/openssl/md4.h
/usr/local/include/node/openssl/md5.h
/usr/local/include/node/openssl/mdc2.h
/usr/local/include/node/openssl/modes.h
/usr/local/include/node/openssl/obj_mac.h
/usr/local/include/node/openssl/objects.h
/usr/local/include/node/openssl/ocsp.h
/usr/local/include/node/openssl/opensslconf.h
/usr/local/include/node/openssl/opensslv.h
/usr/local/include/node/openssl/ossl_typ.h
/usr/local/include/node/openssl/pem.h
/usr/local/include/node/openssl/pem2.h
/usr/local/include/node/openssl/pkcs12.h
/usr/local/include/node/openssl/pkcs7.h
/usr/local/include/node/openssl/pqueue.h
/usr/local/include/node/openssl/rand.h
/usr/local/include/node/openssl/rc2.h
/usr/local/include/node/openssl/rc4.h
/usr/local/include/node/openssl/ripemd.h
/usr/local/include/node/openssl/rsa.h
/usr/local/include/node/openssl/safestack.h
/usr/local/include/node/openssl/seed.h
/usr/local/include/node/openssl/sha.h
/usr/local/include/node/openssl/srp.h
/usr/local/include/node/openssl/srtp.h
/usr/local/include/node/openssl/ssl.h
/usr/local/include/node/openssl/ssl2.h
/usr/local/include/node/openssl/ssl23.h
/usr/local/include/node/openssl/ssl3.h
/usr/local/include/node/openssl/stack.h
/usr/local/include/node/openssl/symhacks.h
/usr/local/include/node/openssl/tls1.h
/usr/local/include/node/openssl/ts.h
/usr/local/include/node/openssl/txt_db.h
/usr/local/include/node/openssl/ui.h
/usr/local/include/node/openssl/ui_compat.h
/usr/local/include/node/openssl/whrlpool.h
/usr/local/include/node/openssl/x509.h
/usr/local/include/node/openssl/x509_vfy.h
/usr/local/include/node/openssl/x509v3.h
/usr/local/include/node/pthread-fixes.h
/usr/local/include/node/stdint-msvc2008.h
/usr/local/include/node/tree.h
/usr/local/include/node/uv-aix.h
/usr/local/include/node/uv-bsd.h
/usr/local/include/node/uv-darwin.h
/usr/local/include/node/uv-errno.h
/usr/local/include/node/uv-linux.h
/usr/local/include/node/uv-sunos.h
/usr/local/include/node/uv-threadpool.h
/usr/local/include/node/uv-unix.h
/usr/local/include/node/uv-version.h
/usr/local/include/node/uv-win.h
/usr/local/include/node/uv.h
/usr/local/include/node/v8-debug.h
/usr/local/include/node/v8-platform.h
/usr/local/include/node/v8-profiler.h
/usr/local/include/node/v8-testing.h
/usr/local/include/node/v8-util.h
/usr/local/include/node/v8-version.h
/usr/local/include/node/v8.h
/usr/local/include/node/v8config.h
/usr/local/include/node/zconf.h
/usr/local/include/node/zlib.h
/usr/local/share/doc/node/gdbinit
/usr/local/share/man/man1/node.1
/usr/local/share/systemtap/tapset/node.stp
==> Caveats
Please note by default only English locale support is provided. If you need
full locale support you should either rebuild with full icu:
  `brew reinstall node --with-full-icu`
or add full icu data at runtime following:
  https://github.com/nodejs/node/wiki/Intl#using-and-customizing-the-small-icu-build

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/6.3.1: 3,829 files, 40.0M
13inch:vulcanscaffold tom$ which node
/usr/local/bin/node
13inch:vulcanscaffold tom$ which node #=> /usr/local/bin/node
/usr/local/bin/node
13inch:vulcanscaffold tom$ export NODE_PATH='/usr/local/lib/node_modules' # add to bashrc if not already there
13inch:vulcanscaffold tom$
13inch:vulcanscaffold tom$
13inch:vulcanscaffold tom$
13inch:vulcanscaffold tom$ open ~/.bash
The file /Users/tom/.bash does not exist.
13inch:vulcanscaffold tom$ open ~/profile
The file /Users/tom/profile does not exist.
13inch:vulcanscaffold tom$ open ~/.profile
13inch:vulcanscaffold tom$ nano  ~/.profile
13inch:vulcanscaffold tom$ yo vulcan
? Your project name generator vulcan
generator vulcan
all done *********************
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/client'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at sync (/Users/tom/GitHub/vulcanscaffold/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/tom/GitHub/vulcanscaffold/node_modules/mkdirp/index.js:77:24)
    at module.exports.yeoman.generators.Base.extend.writing.app (/Users/tom/GitHub/vulcanscaffold/generators/app/index.js:61:12)
    at /Users/tom/GitHub/vulcanscaffold/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback](timers.js:383:17)
13inch:vulcanscaffold tom$ npm update
- word-wrap@1.1.0 node_modules/word-wrap
  generator-vulcan@0.0.2 /Users/tom/GitHub/vulcanscaffold
  ├── chalk@1.1.3
  └── yosay@1.2.0

13inch:vulcanscaffold tom$ npm upgrade
13inch:vulcanscaffold tom$ brew update
Updated 1 tap (homebrew/core).
No changes to formulae.
13inch:vulcanscaffold tom$
13inch:vulcanscaffold tom$
13inch:vulcanscaffold tom$
13inch:vulcanscaffold tom$
13inch:vulcanscaffold tom$ npm install
13inch:vulcanscaffold tom$ npm link
/usr/local/lib/node_modules/generator-vulcan -> /Users/tom/GitHub/vulcanscaffold
13inch:vulcanscaffold tom$ yo vulcan
? Your project name generator vulcan
generator vulcan
all done *********************
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/client'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at sync (/Users/tom/GitHub/vulcanscaffold/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/tom/GitHub/vulcanscaffold/node_modules/mkdirp/index.js:77:24)
    at module.exports.yeoman.generators.Base.extend.writing.app (/Users/tom/GitHub/vulcanscaffold/generators/app/index.js:61:12)
    at /Users/tom/GitHub/vulcanscaffold/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback](timers.js:383:17)
13inch:vulcanscaffold tom$ node -v
v4.4.5
13inch:vulcanscaffold tom$ npm -v
3.10.3
13inch:vulcanscaffold tom$

**Comment by tomachinz** [comment]
I think I just found it..... the darn folder is **owned by root:**

drwxrwxr-x   41 root  wheel       1394  1 Jun 04:31 node

/usr/local/include

After changing back to me:

sudo chown -Rv tom /usr/local/include/node
